// <auto-generated />
using System;
using MachineServiceLab.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineServiceLab.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913043258_SqlServerInitial")]
    partial class SqlServerInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineServiceLab.Api.Data.DiagnosticsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("int");

                    b.Property<double>("BatteryVoltage")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ControllerTemperatureC")
                        .HasColumnType("float");

                    b.Property<string>("FaultCodesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MachineHours")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber", "Id");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("MachineServiceLab.Api.Data.MachineEntity", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SerialNumber");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("MachineServiceLab.Api.Data.TelemetryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber", "Id");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("MachineServiceLab.Api.Data.DiagnosticsEntity", b =>
                {
                    b.HasOne("MachineServiceLab.Api.Data.MachineEntity", null)
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MachineServiceLab.Api.Data.TelemetryEntity", b =>
                {
                    b.HasOne("MachineServiceLab.Api.Data.MachineEntity", null)
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
