// <auto-generated />
using System;
using MachineServiceLab.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineServiceLab.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MachineServiceLab.Api.Data.DiagnosticsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryVoltage")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ControllerTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<string>("FaultCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MachineHours")
                        .HasColumnType("REAL");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("MachineServiceLab.Api.Data.MachineEntity", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
